spring:
  application:
    name: aviation-api

  datasource:
    url: jdbc:postgresql://localhost:5432/aviationdb
    username: aviation
    password: aviation123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 8080